version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"

  order-service:
    build: ./services/order-service
    ports: [ "8080:8080" ]
    depends_on: [ kafka, jaeger, inventory-service, payment-service, shipment-service ]
    environment:
      SPRING_PROFILES_ACTIVE: docker

  inventory-service:
    build: ./services/inventory-service
    ports: [ "8081:8081" ]
    depends_on: [ kafka ]

  payment-service:
    build: ./services/payment-service
    ports: [ "8082:8082" ]
    depends_on: [ kafka ]

  shipment-service:
    build: ./services/shipment-service
    ports: [ "8083:8083" ]
    depends_on: [ kafka ]
